components:
  schemas:
    BaseServiceDTO:
      type: object
      properties:
        prefix:
          type: string
        name:
          type: string
        description:
          type: string
        icon:
          type: string
          format: url
        port:
          type: integer
        driverType:
          $ref: './enums.yaml#/components/schemas/DriverType'
        runCommand:
          description: Command which starts the service
          type: string
          format: bash
        source:
          description: URL to git repository
          type: string
          format: url

    CreateServiceDTO:
      allOf:
        - $ref: '#/components/schemas/BaseServiceDTO'
        - type: object
          required:
            - prefix
            - name
            - port
            - driverType
            - runCommand
            - source

    UpdateServiceDTO:
      allOf:
        - $ref: '#/components/schemas/BaseServiceDTO'
        - type: object

    PublicServiceDTO:
      type: object
      required:
        - prefix
        - name
      properties:
        prefix:
          type: string
        name:
          type: string
        description:
          type: string
        icon:
          type: string
          format: url

    ServiceDTO:
      allOf:
        - $ref: '#/components/schemas/BaseServiceDTO'
        - type: object
          required:
            - id
            - prefix
            - name
            - port
            - driverType
            - runCommand
            - source
          properties:
            id:
              type: string
              format: uuid