openapi: 3.1.0
info:
  title: Secure API Gateway Api
  version: 0.0.1

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

tags:
  - name: Auth
    description: Login and registration for SAS
  - name: Services
    description: Management of SAS services
  - name: Proxy
    description: Proxy endpoint for SAS

paths:
  /auth/login:
    post:
      tags:
        - Auth
      summary: Account login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas.yaml#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login success
          content:
            application/json:
              schema:
                $ref: './schemas.yaml#/components/schemas/LoginResponse'
        '400':
          description: Given login data are wrong or incomplete
          content:
            application/json:
              schema:
                $ref: './schemas.yaml#/components/schemas/ErrorDTO'
        '401':
          description: Account is not authenticated
          content:
            application/json:
              schema:
                $ref: './schemas.yaml#/components/schemas/ErrorDTO'
  /auth/register:
    post:
      tags:
        - Auth
      summary: Create new SAS account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './accountSchemas.yaml#/components/schemas/CreateAccountDTO'
      responses:
        '201':
          description: Account created
          content:
            application/json:
              schema:
                $ref: './accountSchemas.yaml#/components/schemas/AccountDTO'
        '400':
          description: Given account data are wrong or incomplete
          content:
            application/json:
              schema:
                $ref: './schemas.yaml#/components/schemas/ErrorDTO'

  /system/services:
    get:
      tags:
        - Services
      summary: List all services
      responses:
        '200':
          description: List of all services
          content:
            application/json:
              schema:
                $ref: './schemas.yaml#/components/schemas/ServiceDTO'
        '401':
          description: Account is not admin
          content:
            application/json:
              schema:
                $ref: './schemas.yaml#/components/schemas/ErrorDTO'
    post:
      tags:
        - Services
      summary: Add new service
      requestBody:
        content:
          application/json:
            schema:
              $ref: './schemas.yaml#/components/schemas/CreateServiceDTO'
      responses:
        '201':
          description: Service created
          content:
            application/json:
              schema:
                $ref: './schemas.yaml#/components/schemas/ServiceDTO'
        '400':
          description: Given service data are wrong or incomplete
          content:
            application/json:
              schema:
                $ref: './schemas.yaml#/components/schemas/ErrorDTO'
        '401':
          description: Account is not admin
          content:
            application/json:
              schema:
                $ref: './schemas.yaml#/components/schemas/ErrorDTO'
        '409':
          description: Service already with the prefix already exists
          content:
            application/json:
              schema:
                $ref: './schemas.yaml#/components/schemas/ErrorDTO'
