openapi: 3.1.0
info:
  title: SAG internal API
  version: 0.0.1

components:
  schemas:
    ErrorDTO:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string

tags:
  - name: Resources
    description: Endpoints for resources
  - name: Accesses
    description: Management of resource accesses

paths:
  
  # Resources
  
  /internal/{serviceId}/resources:
    post:
      tags:
        - Resources
      summary: Create new resource
      parameters:
        - name: serviceId
          description: Id of calling service
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components/internal/resources.yaml#/components/schemas/CreateResourceDTO'
      responses:
        '201':
          description: Resource created
          content:
            application/json:
              schema:
                $ref: './components/internal/resources.yaml#/components/schemas/ResourceDTO'
  
  /internal/{serviceId}/resources/{resourceId}:
    get:
      tags:
        - Resources
      summary: Detail of resource
      parameters:
        - name: serviceId
          description: Id of calling service
          in: path
          required: true
          schema:
            type: string
        - name: resourceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detail of resource
          content:
            application/json:
              schema:
                $ref: './components/internal/resources.yaml#/components/schemas/ResourceDTO'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
    patch:
      tags:
        - Resources
      summary: Update resource
      parameters:
        - name: serviceId
          description: Id of calling service
          in: path
          required: true
          schema:
            type: string
        - name: resourceId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components/internal/resources.yaml#/components/schemas/UpdateResourceDTO'
      responses:
        '200':
          description: Resource updated
          content:
            application/json:
              schema:
                $ref: './components/internal/resources.yaml#/components/schemas/ResourceDTO'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
    delete:
      tags:
        - Resources
      summary: Delete resource and it's accesses
      parameters:
        - name: serviceId
          description: Id of calling service
          in: path
          required: true
          schema:
            type: string
        - name: resourceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Resource and it's accesses deleted
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'

  # Accesses

  /internal/{serviceId}/access:
    put:
      tags:
        - Accesses
      summary: Set resource access (recursively)
      parameters:
        - name: serviceId
          description: Id of calling service
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components/internal/resource_access.yaml#/components/schemas/ResourceAccessDTO'
      responses:
        '200':
          description: Access set
          content:
            application/json:
              schema:
                $ref: './components/internal/resource_access.yaml#/components/schemas/SetResourceAccessDTO'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'

  /internal/{serviceId}/access/{accountId}:
    post:
      tags:
        - Accesses
      summary: Decides if account can read resources
      parameters:
        - name: serviceId
          description: Id of calling service
          in: path
          required: true
          schema:
            type: string
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
                format: uuid
      responses:
        '200':
          description: List of resource accesses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './components/internal/resource_access.yaml#/components/schemas/ResourceAccessDTO'
        '404':
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'